#      _              _     _   ____                          _
#     / \     _ __   | |_  (_) |  _ \    ___    __ _    ___  | |__
#    / _ \   | '_ \  | __| | | | |_) |  / _ \  / _` |  / __| | '_ \
#   / ___ \  | | | | | |_  | | |  _ <  |  __/ | (_| | | (__  | | | |
#  /_/   \_\ |_| |_|  \__| |_| |_| \_\  \___|  \__,_|  \___| |_| |_|
#  A free and high quality Anti Reach solution

#<p> is replaceable to ● and <s> is replaceable to ┃
#<pk> is replaceable to •
#>> is replaceable to »
#<<  is replaceable to «
#<st> is replaceable to ×
#<d> is replaceable to ►
#<sb> is replaceable to ▎
Prefix: "&8<sb> &9AntiReach &8<d>"

General:
  #Here are the important news.
  #Message come when someone makes / ac and has no rights.
  own-permissions-message: false
  NoPermissions: "%prefix% &cYou dont have permissions to do that."
  #Message comes when the console / ac does.
  NoPlayer: "%prefix% &cYou must be a player to execute this command."

Messages:
  #Standard messages can be changed here.
  #Color codes are indicated with & and are thus translated
  Plugin: "%prefix% &7Plugin was sucessfully reloaded"

Checks:
  A:
    enable: true
    maxreach: 4.3
  B:
    enable: true
    maxreach: 4.1
  C:
    enable: true
    maxreach: 4.0
  D:
    enable: true
    maxreach: 4.2
  E:
    enable: true
    maxreach: 3.9
  HitDirection:
    #This Check is currently in beta | enable it on your own responsibility
    enable: false
    hitBoxLenght: 1.05
    normX: 0.5
    normY: 0.5

Permissions:
  #Not covered by this system.
  bypass: "AntiReach.bypass"
  #Can execute all commands and is not captured by this system. | also get the Verbose messages from the system.
  admin: "AntiReach.admin"
  #Get only the verbose messages from the system.
  verbose: "AntiReach.verbose"

Settings:
  #Can spam the console full of news.
  #Use it at your own risk!
  console-log: false
  #Set player pitch to -90F on check
  reset-player-pitch: true
  #Edit the Settings for the Check: HitDirection
  HitDirection:
    min-level-to-kick: 30
    kick-command: "kick %name% %prefix% &7We have detected you with HitDirection"
  #Edit the Settings for the Check: Reach
  Reach:
    min-level-to-kick: 30
    kick-command: "kick %name% %prefix% &7We have detected you with Reach &8[&e%reach%&8]"