#      _              _     _   ____                          _
#     / \     _ __   | |_  (_) |  _ \    ___    __ _    ___  | |__
#    / _ \   | '_ \  | __| | | | |_) |  / _ \  / _` |  / __| | '_ \
#   / ___ \  | | | | | |_  | | |  _ <  |  __/ | (_| | | (__  | | | |
#  /_/   \_\ |_| |_|  \__| |_| |_| \_\  \___|  \__,_|  \___| |_| |_|
#  A free and high quality Anti Reach solution

#<p> is replaceable to ● and <s> is replaceable to ┃
#<pk> is replaceable to •
#>> is replaceable to »
#<<  is replaceable to «
#<st> is replaceable to ×
#<d> is replaceable to ►
#<sb> is replaceable to ▎
Prefix: "&8<sb> &cAntiReach &8<d>"

General:
  #Here are the important news.
  #Message come when someone makes / ac and has no rights.
  own-permissions-message: false
  NoPermissions: "%prefix% &cYou dont have permissions to do that."

Permissions:
  #Not covered by this system.
  bypass: "AntiReach.bypass"
  #Can execute all commands and is not captured by this system. | also get the Verbose messages from the system.
  admin: "AntiReach.admin"
  #Get only the verbose messages from the system.
  verbose: "AntiReach.verbose"

Settings:
  #Can spam the console full of news.
  #Use it at your own risk!
  console-log: false
  #Set player pitch to -90F on check
  reset-player-pitch: true
  #Create a log file from a player when he get kicked
  logFile: true
  #Edit the Settings for the Check: Reach
  Reach:
    min-level-to-kick: 30
    own-kick-command: false
    kick-command: "kick %name% %prefix% &7We have detected you with Reach &8[&e%reach%&8]"