name: AntiReach
version: 5.0-BETA
description: a free and high quality anti reach solution
authors: [SquareCode, Tomekk, reax]
main: net.square.main.AntiReach
website: https://www.spigotmc.org/members/squarecode.564161/

commands:
  antireach:
    description: Main command of the plugin
    aliases: [ac, ar]